### PR TITLE
added basics examples and Toree notebook how to do

### PR DESCRIPTION
**Pull request by Mageswaran1989**
Hi,

I moved from old branch (https://github.com/eaplatanios/tensorflow_scala/pull/23)  to current branch after couple of explorartion on presenting the examples in Jupyer Notebook environment.

Notebook view @ https://github.com/iaja/tensorflow_scala/blob/examples/cookbook/Tensors%20and%20PlaceHolders.ipynb

I managed that with older version of tensorflow_scala library.

Need your "ATTENTION" to continue further, as with latest branch I am not able to compile!

Waiting @  https://gitter.im/tensorflow_scala/Lobby for more chats!

### CODE REVIEW

**Comment by eaplatanios** [comment]
@Mageswaran1989 Sorry for the delay with integrating this but I was dealing with lots of stuff and I prioritized getting a release ready that works for all pre-compiled binaries. Can you please test and verify that your code and examples with work with the `0.1.1` release (not the snapshot one)?

**Comment by Mageswaran1989** [comment]
Got into some official work, will look into this and revert ASAP.

**Comment by eaplatanios** [comment]
@Mageswaran1989 Do you plan to update this for the current version? If not, I'll have to close it. I have plans to make some tutorials soon.

**Comment by Mageswaran1989** [comment]
@eaplatanios I am resuming the work! Please let me know your inputs if you have any.

**Comment by mageswarandhandapani** [comment]
@eaplatanios 

I am getting following linker error:
Caused by: org.platanios.tensorflow.jni.NotFoundException: /tmp/tensorflow_scala_native_libraries1309267377490548090/libtensorflow_ops.so: undefined symbol: _ZN10tensorflow20OpKernelConstruction21CtxFailureWithWarningEPKciRKNS_6StatusE
	at org.platanios.tensorflow.jni.TensorFlow$.loadOpLibrary(Native Method)
	at org.platanios.tensorflow.jni.TensorFlow$.$anonfun$load$6(TensorFlow.scala:107)
	at scala.Option.foreach(Option.scala:257)


can you share your env details?

**Comment by Mageswaran1989** [comment]
Closing this as this has some merge conflicts

**Pull request closed without merging**
